source "http://rubygems.org"

# for running rake assets:resprite
group :resprite do
  gem "sprite-factory", "1.7.1"
  gem "chunky_png",     "1.4.0"
end

# for running rake assets:server
group :server do
  gem "unified-assets", "0.0.1"
  gem "rack",           "3.0.7"
  gem "thin",           "1.8.2"
end
